apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-mvp-component-gyhf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-mvp-component-gyhf
    app.kubernetes.io/part-of: mvp-test-app
  name: test-mvp-component-gyhf
  namespace: mvp-demo-dev-namespace-hznl-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-mvp-component-gyhf
    weight: 100
status: {}
